# Generated by Django 4.2.13 on 2024-05-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gravar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=150)),
                ('nascido', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
    ]
