# Generated by Django 4.2.13 on 2024-06-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='boletim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('matematica', models.CharField(max_length=2)),
                ('portugues', models.CharField(max_length=2)),
                ('fisica', models.CharField(max_length=2)),
                ('quimica', models.CharField(max_length=2)),
                ('ingles', models.CharField(max_length=2)),
                ('geografia', models.CharField(max_length=2)),
                ('historia', models.CharField(max_length=2)),
                ('ciencias', models.CharField(max_length=2)),
            ],
        ),
    ]
