# Generated by Django 4.2.13 on 2024-07-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_boletim2b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletimb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=200)),
                ('ciencias_bim1', models.FloatField()),
                ('ciencias_bim2', models.FloatField()),
                ('ciencias_bim3', models.FloatField()),
                ('ciencias_bim4', models.FloatField()),
                ('matematica_bim1', models.FloatField()),
                ('matematica_bim2', models.FloatField()),
                ('matematica_bim3', models.FloatField()),
                ('matematica_bim4', models.FloatField()),
                ('geografia_bim1', models.FloatField()),
                ('geografia_bim2', models.FloatField()),
                ('geografia_bim3', models.FloatField()),
                ('geografia_bim4', models.FloatField()),
                ('historia_bim1', models.FloatField()),
                ('historia_bim2', models.FloatField()),
                ('historia_bim3', models.FloatField()),
                ('historia_bim4', models.FloatField()),
                ('portugues_bim1', models.FloatField()),
                ('portugues_bim2', models.FloatField()),
                ('portugues_bim3', models.FloatField()),
                ('portugues_bim4', models.FloatField()),
                ('ingles_bim1', models.FloatField()),
                ('ingles_bim2', models.FloatField()),
                ('ingles_bim3', models.FloatField()),
                ('ingles_bim4', models.FloatField()),
                ('fisica_bim1', models.FloatField()),
                ('fisica_bim2', models.FloatField()),
                ('fisica_bim3', models.FloatField()),
                ('fisica_bim4', models.FloatField()),
                ('quimica_bim1', models.FloatField()),
                ('quimica_bim2', models.FloatField()),
                ('quimica_bim3', models.FloatField()),
                ('quimica_bim4', models.FloatField()),
            ],
        ),
    ]
