# Generated by Django 4.2.13 on 2024-07-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_boletimb'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletimb',
            name='matricula',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='ciencias_bim1',
            field=models.FloatField(max_length=2),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='ciencias_bim2',
            field=models.FloatField(max_length=2),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='ciencias_bim3',
            field=models.FloatField(max_length=2),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='ciencias_bim4',
            field=models.FloatField(max_length=2),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='matematica_bim1',
            field=models.FloatField(max_length=2),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='matematica_bim2',
            field=models.FloatField(max_length=2),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='matematica_bim3',
            field=models.FloatField(max_length=2),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='matematica_bim4',
            field=models.FloatField(max_length=2),
        ),
    ]
