# Generated by Django 4.2.13 on 2024-07-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_boletimb_matricula_alter_boletimb_ciencias_bim1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletimb',
            name='ciencias_bim2',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='ciencias_bim3',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='ciencias_bim4',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='fisica_bim2',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='fisica_bim3',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='fisica_bim4',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='geografia_bim2',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='geografia_bim3',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='geografia_bim4',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='historia_bim2',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='historia_bim3',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='historia_bim4',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='ingles_bim2',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='ingles_bim3',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='ingles_bim4',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='matematica_bim2',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='matematica_bim3',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='matematica_bim4',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='portugues_bim2',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='portugues_bim3',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='portugues_bim4',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='quimica_bim2',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='quimica_bim3',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='boletimb',
            name='quimica_bim4',
            field=models.FloatField(blank=True, max_length=2, null=True),
        ),
    ]
